### ISSUE TITLE
Cannot install new R packages via command (maybe already fixed?)

### ISSUE THREAD

**Issue by raddick** [sciserver/SciScript-R#1]
This was a helpdesk question from a while ago - it may have been fixed already. Just want to make sure that it gets tracked.

---

Issue title:
install R packages

Category: Feature request

Severity: Moderate

Description:
Cannot install new R packages via command. It may work to just add a environmental variable "R_LIBS"(http://www.stat.osu.edu/computer-support/mathstatistics-packages/installing-r-libraries-locally-your-home-directory)
that points at some user accessible directory. It might be nice to push that into a persistent directory so that you do not have to keep installing different packages for each new container.

Steps to reproduce:
1. Start a new R notebook
2. Run "install.packages('ggplot2')"
3. Fails to install
4. Error:
"
Warning message:
In install.packages("ggplot2"): 'lib = "/usr/lib64/MRO-3.2.3/R-3.2.3/lib64/R/library"' is not writable
Error in install.packages("ggplot2"): unable to install packages
"

**Comment by dmedv** [comment]
Duplicate issue: 
https://github.com/sciserver/sciserver-compute/issues/9
